language: python

python:
  - "2.7"
  - "2.6"

env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.2

install:
  - pip install Django==$DJANGO
  - python setup.py develop

script: python setup.py test
